import { Listing, Monetization } from '../types';

export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'mock-1',
    title: 'Luxury 4 Bedroom Villa with Swimming Pool',
    price: 450000,
    currency: 'USD',
    location: 'East Legon, Accra, Ghana',
    country: 'GH',
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'
    ],
    categoryId: 'houses',
    subcategoryId: 'houses-res',
    isFeatured: true,
    isPremium: true,
    datePosted: new Date(Date.now() - 86400000 * 2).toISOString(),
    expiryDate: new Date(Date.now() + 86400000 * 60).toISOString(),
    sellerId: 'agent-1',
    description: 'Modern luxury villa situated in the heart of East Legon. Features 4 ensuite bedrooms, infinity pool, smart home automation, 24/7 high security, and landscaped gardens.',
    status: 'active',
    type: 'Sale',
    propertyType: 'Villa',
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4200,
    amenities: ['Swimming Pool', 'Security Guard', 'Backup Generator', 'Smart Home', 'Air Conditioning', 'Gated Community'],
    furnished: true,
    parking: true,
    security: true,
    petsAllowed: true,
    yearBuilt: 2023,
    isVerified: true
  },
  {
    id: 'mock-2',
    title: 'Executive 2 Bedroom Apartment in Cantonments',
    price: 2200,
    currency: 'USD',
    location: 'Cantonments, Accra, Ghana',
    country: 'GH',
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    categoryId: 'houses',
    subcategoryId: 'apartments',
    isFeatured: true,
    isPremium: false,
    datePosted: new Date(Date.now() - 86400000 * 5).toISOString(),
    expiryDate: new Date(Date.now() + 86400000 * 30).toISOString(),
    sellerId: 'agent-2',
    description: 'Fully furnished executive 2 bedroom apartment in prestigious Cantonments. Perfect for diplomats, expatriates, and corporate executives.',
    status: 'active',
    type: 'Rent',
    propertyType: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1400,
    amenities: ['Gym', 'Pool', 'Elevator', '24/7 Power', 'High Speed Wifi'],
    furnished: true,
    parking: true,
    security: true,
    petsAllowed: false,
    yearBuilt: 2022,
    isVerified: true
  },
  {
    id: 'mock-3',
    title: 'Prime Serviced Commercial Plot in Spintex',
    price: 180000,
    currency: 'USD',
    location: 'Spintex Road, Accra, Ghana',
    country: 'GH',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80'
    ],
    categoryId: 'land',
    subcategoryId: 'commercial-plots',
    isFeatured: false,
    isPremium: true,
    datePosted: new Date(Date.now() - 86400000 * 10).toISOString(),
    expiryDate: new Date(Date.now() + 86400000 * 45).toISOString(),
    sellerId: 'agent-1',
    description: '0.5 acre commercial land with clean land title registry documentation along the busy Spintex road corridor. Ideal for showroom, warehouse or plaza.',
    status: 'active',
    type: 'Sale',
    propertyType: 'Land',
    sqft: 21780,
    amenities: ['Road Access', 'Electricity Connected', 'Water Supply', 'Clear Title'],
    isVerified: true
  },
  {
    id: 'mock-4',
    title: 'Modern Grade-A Office Space in Ridge',
    price: 35,
    currency: 'USD',
    location: 'North Ridge, Accra, Ghana',
    country: 'GH',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80'
    ],
    categoryId: 'offices',
    subcategoryId: 'private-offices',
    isFeatured: true,
    isPremium: false,
    datePosted: new Date(Date.now() - 86400000 * 3).toISOString(),
    expiryDate: new Date(Date.now() + 86400000 * 60).toISOString(),
    sellerId: 'agent-3',
    description: 'Open plan Grade-A corporate office suite in prime financial district. Price per sqm/month. Features fibre internet, central AC, underground parking.',
    status: 'active',
    type: 'Rent',
    propertyType: 'Office',
    sqft: 3500,
    amenities: ['Central AC', 'Underground Parking', 'Backup Generator', 'CCTV Security'],
    isVerified: true
  },
  {
    id: 'mock-5',
    title: 'Spacious Industrial Warehouse in Tema Heavy Industrial Area',
    price: 12000,
    currency: 'USD',
    location: 'Tema, Ghana',
    country: 'GH',
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80'
    ],
    categoryId: 'warehouses',
    subcategoryId: 'warehouses-ind',
    isFeatured: false,
    isPremium: false,
    datePosted: new Date(Date.now() - 86400000 * 7).toISOString(),
    expiryDate: new Date(Date.now() + 86400000 * 90).toISOString(),
    sellerId: 'agent-2',
    description: '2,500 sqm high bay industrial warehouse with loading bays, office section, and heavy power supply near Tema Port.',
    status: 'active',
    type: 'Rent',
    propertyType: 'Warehouse',
    sqft: 26900,
    amenities: ['High Ceiling', 'Loading Bay', 'Heavy Industrial Power', '24/7 Yard Security'],
    isVerified: true
  }
];

export const MOCK_ADS: Monetization[] = [
  {
    id: 'mock-ad-1',
    title: 'Standard Chartered Home Loans',
    description: 'Get competitive interest rates on home financing up to 20 years.',
    cta: 'Apply Now',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1200&q=80',
    link: 'https://www.sc.com',
    color: 'blue',
    priority: 1,
    type: 'banner',
    active: true,
    countryCode: 'GH',
    impressions: 1240,
    clicks: 85,
    createdAt: new Date().toISOString()
  }
];
